name: Open quarkus-platform PR

on:
  workflow_call:
    inputs:
      qosdk-version:
        type: string
        required: true
      quarkus-version:
        type: string
        required: true
      quarkus-platform-branch:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: quarkusio/quarkus-platform
          path: quarkus-platform

      - name: Update QOSDK version to ${{inputs.qosdk-version}} in quarkus-platform ${{inputs.quarkus-platform-branch}}
        run: |
          cd quarkus-platform
          git checkout ${{inputs.quarkus-platform-branch}}
          mvn -B versions:set-property -Dproperty=quarkus-operator-sdk.version -DnewVersion=${{inputs.qosdk-version}}
          ./mvnw -Dsync

      - name: Create quarkus-platform pull request
        uses: peter-evans/create-pull-request@v5
        id: qp-pr
        with:
          path: quarkus-platform
          title: "Update QOSDK to ${{inputs.qosdk-version}} for ${{inputs.quarkus-platform-branch}}"
          commit-message: "Update QOSDK to ${{inputs.qosdk-version}}"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{inputs.qosdk-version}}-${{inputs.quarkus-platform-branch}}
          token: ${{ secrets.QOSDK_BOT_TOKEN }}
          push-to-fork: qosdk-bot/quarkus-platform
          delete-branch: true

      - name: Check quarkus-platform PR
        if: ${{ steps.qp-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.qp-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.qp-pr.outputs.pull-request-url }}"

      - name: Check if Quarkus Platform PR also needs to be opened on main
        if: "${{ inputs.quarkus-platform-branch != 'main' }}"
        id: need-main-pr-check
        run: |
          qosdk_latest=$(curl -sL https://api.github.com/repos/quarkiverse/quarkus-operator-sdk/releases/latest | jq -r ".tag_name")
          echo "Latest QOSDK release: ${qosdk_latest}"
          if [ "${{inputs.qosdk-version}}" = "${qosdk_latest}" ]; then
            echo "need_main_pr=true" >> $GITHUB_OUTPUT
          else
            echo "No need for PR on quarkus-platform main"
          fi

      - name: Update QOSDK version to ${{inputs.qosdk-version}} in quarkus-platform main
        if: "${{steps.need-main-pr-check.outputs.need_main_pr == 'true'}}"
        run: |
          cd quarkus-platform
          git reset --hard origin/main
          mvn -B versions:set-property -Dproperty=quarkus-operator-sdk.version -DnewVersion=${{inputs.qosdk-version}}
          ./mvnw -Dsync

      - name: Create quarkus-platform pull request
        if: "${{steps.need-main-pr-check.outputs.need_main_pr == 'true'}}"
        uses: peter-evans/create-pull-request@v5
        id: qp-pr-main
        with:
          path: quarkus-platform
          title: "Update QOSDK to ${{inputs.qosdk-version}}"
          commit-message: "Update QOSDK to ${{inputs.qosdk-version}}"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{inputs.qosdk-version}}
          token: ${{ secrets.QOSDK_BOT_TOKEN }}
          push-to-fork: qosdk-bot/quarkus-platform
          delete-branch: true

      - name: Check main quarkus-platform PR
        if: ${{ steps.qp-pr-main.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.qp-pr-main.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.qp-pr-main.outputs.pull-request-url }}"