name: Release snapshots of selected branches on push

on:
  push:
    branches: [ main, next, next-fabric8-version ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  release-snapshot:
    uses: ./.github/workflows/release-snapshot.yml
    with:
      branch: "${{github.ref}}"