name: Release snapshot of next-fabric8-version branch each day at midnight

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-for-latest-quarkus-version:
    uses: ./.github/workflows/build-for-quarkus-version.yml
    with:
      quarkus-version-jq-cmd: '.platforms[0]."current-stream-id" as $current | .platforms[0].streams[] | select(.id == $current) | .releases[0].version'
      java-version: 21
      branch: "next-fabric8-version"
      native-modules: "integration-tests,samples"
      profiles: "use-snapshots"

  release-snapshot:
    uses: ./.github/workflows/release-snapshot.yml
    with:
      branch: "next-fabric8-version"
      version: "999.F8-SNAPSHOT"
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}